name: Deploy Server to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-server:
    name: Deploy server via FTP to CPanel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for server
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies for server
        run: cd server && npm install

      - name: Build the server project
        run: cd server && npm run build

      - name: FTP Deploy server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER_TARGET_HOST }}
          username: ${{ secrets.FTP_SERVER_USERNAME }}
          password: ${{ secrets.FTP_SERVER_PASSWORD }}
          local-dir: ./server/
          server-dir: /

  enforce-deploy:
    name: Enforce Successful Deploy
    runs-on: ubuntu-latest
    needs: [deploy-server]
    steps:
      - name: Confirm deploy success
        run: echo "✅ Server deployed successfully to production!"
