name: CI - Build Vite on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Vite Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm' # Ou 'yarn' si vous utilisez Yarn

      - name: Install dependencies
        run: npm install # Remplacez par `yarn install` si vous utilisez Yarn

      - name: Build the project
        run: npm run build # Remplacez par `yarn build` si vous utilisez Yarn

  enforce-build:
    name: Enforce Build Pass
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Ensure successful build
        run: echo "Build successful, PR can be merged"
