name: CI - Build Nest + FTP Deploy on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-server:
    name: Build Nest Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for server
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies for server
        run: cd server && npm install

      - name: Build the server project
        run: cd server && npm run build

  deploy-server:
    name: Deploy server via FTP to CPanel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: FTP Deploy server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER_TARGET_HOST }}
          username: ${{ secrets.FTP_SERVER_USERNAME }}
          password: ${{ secrets.FTP_SERVER_PASSWORD }}
          local-dir: ./server/
          server-dir: /

  enforce-build:
    name: Enforce Successful Build & Deploy
    runs-on: ubuntu-latest
    needs: [deploy-server]
    steps:
      - name: Confirm build & deploy success
        run: echo "✅ Server build deployed successfully!"
