name: CI - Build Nest on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-client:
    name: Build Vite Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for client
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies for client
        run: cd client && npm install

      - name: Build the client project
        run: cd client && npm run build

  build-server:
    name: Build Nest Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for server
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies for server
        run: cd server && npm install

      - name: Build the server project
        run: cd server && npm run build

enforce-build:
  name: Enforce Successful Build
  runs-on: ubuntu-latest
  needs: [build-client, build-server]
  steps:
    - name: Confirm build success
      run: echo "✅ Both client and server builds are successful, PR can be merged"
